# Adapted from https://github.com/commitizen-tools/commitizen/blob/4060cc22d47761e2b5015b5f2d2484c3d65f92a5/.github/workflows/docspublish.yaml
name: Publish documentation

on:
  push:
# FIXME[AA]:any branch, to test until it works
#    branches:
#      - master

jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
        #   fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install -U mkdocs mkdocs-material
      - name: Build docs --strict --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -m mkdocs build --strict
      - name: Push docs to Github Pages
        # Run "invoke mkdocs.deploy" to create the "gh-pages" branch and deploy it first, otherwise this step fails
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
